version: '3'

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - backend

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - backend

networks:
  backend:
    driver: bridge
